<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Holycow\Module'                          => __DIR__ . '/Module.php',
    'Holycow\Controller\CommandesController'  => __DIR__ . '/src/Holycow/Controller/CommandesController.php',
    'Holycow\Controller\LivraisonsController' => __DIR__ . '/src/Holycow/Controller/LivraisonsController.php',
    'Holycow\Entity\Commandes'                => __DIR__ . '/src/Holycow/Entity/Commandes.php',
    'Holycow\Entity\Livraisons'               => __DIR__ . '/src/Holycow/Entity/Livraisons.php',
    'Holycow\Form\CommandeFieldset'           => __DIR__ . '/src/Holycow/Form/CommandeFieldset.php',
    'Holycow\Form\CommandeForm'               => __DIR__ . '/src/Holycow/Form/CommandeForm.php',
    'Holycow\Form\LivraisonFieldset'          => __DIR__ . '/src/Holycow/Form/LivraisonFieldset.php',
    'Holycow\Form\LivraisonForm'              => __DIR__ . '/src/Holycow/Form/LivraisonForm.php',
    'Holycow\Strategy\DateToStringStrategy'   => __DIR__ . '/src/Holycow/Strategy/DateToStringStrategy.php',
    'HolycowTest\Framework\TestCase'          => __DIR__ . '/tests/Holycow/Framework/TestCase.php',
    'HolycowTest\SampleTest'                  => __DIR__ . '/tests/Holycow/SampleTest.php',
);